# Generated by Django 2.1.8 on 2020-06-04 01:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyInBooking',
            fields=[
                ('buy_in_id', models.UUIDField(default=uuid.UUID('939bd88c-b3e9-4a35-9e96-8fffc2bde11a'), editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PickUpBooking',
            fields=[
                ('pick_up_id', models.UUIDField(default=uuid.UUID('0bc8102e-4088-4128-9f67-1d83e4c0c839'), editable=False, primary_key=True, serialize=False)),
                ('message_for_shopkeeper', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickUpNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_time', models.TimeField(auto_now=True)),
                ('pickup_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupnotif', to='main.PickUpBooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupnotif', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-notif_time'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_name', models.CharField(max_length=60)),
                ('gst_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('shop_capacity', models.IntegerField()),
                ('owner_name', models.CharField(max_length=120)),
                ('owner_phone_number', models.CharField(max_length=10)),
                ('shop_pincode', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('shop_city', models.CharField(max_length=150)),
                ('shop_area', models.CharField(max_length=500)),
                ('shop_street', models.CharField(max_length=150)),
                ('shop_state', models.CharField(max_length=25)),
                ('slot_duration', models.IntegerField(default=15)),
                ('give_whatsapp_order', models.BooleanField(default=False)),
                ('shop_type', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('slot_start_time', models.DateTimeField()),
                ('slot_stop_time', models.DateTimeField()),
                ('num_entries_left', models.IntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='main.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='pickupbooking',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupbookings', to='main.Shop'),
        ),
        migrations.AddField(
            model_name='pickupbooking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupbookings', to='main.Slot'),
        ),
        migrations.AddField(
            model_name='pickupbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupbookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyinbooking',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyinbookings', to='main.Shop'),
        ),
        migrations.AddField(
            model_name='buyinbooking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyinbookings', to='main.Slot'),
        ),
        migrations.AddField(
            model_name='buyinbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyinbookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
