# Generated by Django 3.0.6 on 2020-05-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
