# Generated by Django 2.1.8 on 2020-06-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupbooking',
            name='message_for_shopkeeper',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
