# Generated by Django 2.1.8 on 2020-05-24 19:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='slot_id',
            field=models.UUIDField(default=uuid.UUID('d7dc735a-4c53-4608-83d9-22a225f241bb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
