# Generated by Django 2.1.8 on 2020-06-10 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200608_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakday', to='main.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
    ]
