# Generated by Django 2.1.8 on 2020-05-26 08:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200525_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='slot_id',
            field=models.UUIDField(default=uuid.UUID('53c73dc8-6ec3-466c-95f2-ee6d81733ff1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
