# Generated by Django 3.0.6 on 2020-05-14 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200514_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_pincode',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
