# Generated by Django 2.1.8 on 2020-05-26 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20200526_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyInBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyinbookings', to='main.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='PickUpBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_for_shopkeeper', models.CharField(max_length=256, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupbookings', to='main.Shop')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_id',
            field=models.UUIDField(default=uuid.UUID('09e9414f-c7b2-44cc-9b35-6eac036e911b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddField(
            model_name='pickupbooking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupbookings', to='main.Slot'),
        ),
        migrations.AddField(
            model_name='pickupbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupbookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyinbooking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyinbookings', to='main.Slot'),
        ),
        migrations.AddField(
            model_name='buyinbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyinbookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
