# Generated by Django 2.1.8 on 2020-07-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200705_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='gpay_number',
            field=models.CharField(default='N/A', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owners_remark',
            field=models.CharField(default='N/A', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='paytm_number',
            field=models.CharField(default='N/A', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phonepe_number',
            field=models.CharField(default='N/A', max_length=10, null=True),
        ),
    ]
