# Generated by Django 2.1.8 on 2020-05-26 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200526_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyinbooking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pickupbooking',
            name='id',
        ),
        migrations.AddField(
            model_name='buyinbooking',
            name='buy_in_id',
            field=models.UUIDField(default=uuid.UUID('ff02ec86-ef1a-4c3a-ba2c-774ca843d668'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pickupbooking',
            name='pick_up_id',
            field=models.UUIDField(default=uuid.UUID('20a89b45-5146-4611-8484-6f12a1598ce0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_id',
            field=models.UUIDField(default=uuid.UUID('4be5a34f-22da-46da-97fe-0dd0ab1b3dff'), editable=False, primary_key=True, serialize=False),
        ),
    ]
