# Generated by Django 2.1.8 on 2020-07-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200705_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupbooking',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
