# Generated by Django 2.1.8 on 2020-05-26 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200526_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyinbooking',
            name='buy_in_id',
            field=models.UUIDField(default=uuid.UUID('6fc76081-2765-4a06-8565-eb1669a1159a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pickupbooking',
            name='pick_up_id',
            field=models.UUIDField(default=uuid.UUID('de808a6d-298b-420d-b0c7-ba6b5727bebc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_id',
            field=models.UUIDField(default=uuid.UUID('9db2785e-4003-49db-b0fa-7a73be7fc665'), editable=False, primary_key=True, serialize=False),
        ),
    ]
