# Generated by Django 2.1.8 on 2020-05-26 12:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200526_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='buyinbooking',
            name='buy_in_id',
            field=models.UUIDField(default=uuid.UUID('f1dc97a4-25dc-4291-977d-74438e9864d6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pickupbooking',
            name='pick_up_id',
            field=models.UUIDField(default=uuid.UUID('13926acb-1c04-4970-ba25-d1711889b4dd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_id',
            field=models.UUIDField(default=uuid.UUID('3d43b3fd-8740-479d-9029-20aa19fe37ee'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pickupnotification',
            name='pickup_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupnotif', to='main.PickUpBooking'),
        ),
        migrations.AddField(
            model_name='pickupnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupnotif', to='main.Shop'),
        ),
    ]
