# Generated by Django 2.1.8 on 2020-05-26 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200526_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyinbooking',
            name='buy_in_id',
            field=models.UUIDField(default=uuid.UUID('c3a3269a-d45b-440b-b223-be26de8dcec3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pickupbooking',
            name='pick_up_id',
            field=models.UUIDField(default=uuid.UUID('2b16cf4f-bfe8-4754-bfac-7821382440b5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_id',
            field=models.UUIDField(default=uuid.UUID('ae68bb11-10c7-4e5f-88dd-c60120e01378'), editable=False, primary_key=True, serialize=False),
        ),
    ]
