# Generated by Django 2.1.8 on 2020-05-26 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200526_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyinbooking',
            name='buy_in_id',
            field=models.UUIDField(default=uuid.UUID('b66b34e3-37bd-47af-99ab-54c2f38b4f36'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pickupbooking',
            name='pick_up_id',
            field=models.UUIDField(default=uuid.UUID('7d0790e0-10cf-45cb-b6ae-3029c7a75e52'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_id',
            field=models.UUIDField(default=uuid.UUID('e1f4a2de-1cd0-4fb8-8afc-7e6d03b44b40'), editable=False, primary_key=True, serialize=False),
        ),
    ]
