# Generated by Django 2.1.8 on 2020-05-26 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200526_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyinbooking',
            name='buy_in_id',
            field=models.UUIDField(default=uuid.UUID('c9a10a9e-8f12-40e3-80ac-8e4a60a00d4a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pickupbooking',
            name='pick_up_id',
            field=models.UUIDField(default=uuid.UUID('fb83f199-398f-4156-a1f2-02d1709abed1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_id',
            field=models.UUIDField(default=uuid.UUID('94afa5c0-171f-4afb-a6e5-dfcdac24cf62'), editable=False, primary_key=True, serialize=False),
        ),
    ]
