# Generated by Django 2.1.8 on 2020-05-26 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200526_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyinbooking',
            name='buy_in_id',
            field=models.UUIDField(default=uuid.UUID('014f8735-2e8d-47ba-8f7a-1e105f26d874'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pickupbooking',
            name='pick_up_id',
            field=models.UUIDField(default=uuid.UUID('3970379a-a83a-4031-8688-3811aa4c47c5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pickupnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupnotif', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_id',
            field=models.UUIDField(default=uuid.UUID('0bbbefd0-87c7-42c0-9d15-9dd6fa44f897'), editable=False, primary_key=True, serialize=False),
        ),
    ]
