# Generated by Django 2.1.8 on 2020-05-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ph_number',
            field=models.CharField(max_length=10),
        ),
    ]
