# Generated by Django 2.1.8 on 2020-05-20 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHONE_OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number not correct!', regex='^\\(|\\)|\\d{10}$')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
    ]
