# Generated by Django 2.1.8 on 2020-05-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
