# Generated by Django 2.1.8 on 2020-05-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_phone_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PHONE_OTP',
            new_name='PhoneOTP',
        ),
    ]
