# Generated by Django 2.1.8 on 2020-05-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_phoneotp_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
