# Generated by Django 2.1.8 on 2020-05-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_phoneotp_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ph_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
